name: ~Reusable Example
on:
  workflow_call:
    inputs:
      workflow-context:
        type: string

permissions:
  actions: read  # required for qoomon/actions--context action
  deployments: read  # required for qoomon/actions--context action
  contents: read

jobs:
  build-with-reusable-workflow:
    uses: ./.github/workflows/example-reusable.yml
    with:
      # IMPORTANT "job" value must match the surrounding job name
      # IMPORTANT If the surrounding workflow is a reusable workflow itself,
      #   add ${{ inputs.workflow-context }} as an additional line of input value
      workflow-context: |
        { "job": "build-with-reusable-workflow", "matrix": ${{ toJSON(matrix) }} }
        ${{ inputs.workflow-context }}
