name: ~ Reusable Example Nested
on:
  workflow_call:
    inputs:
      workflow-context:
        type: string

permissions:
  actions: read  # required for qoomon/actions--context action
  deployments: read  # required for qoomon/actions--context action
  contents: read

jobs:
  build-with-reusable-workflow:
    uses: ./.github/workflows/example-reusable.yml
    with:
      # IMPORTANT ensure first value match the surrounding job name
      # IMPORTANT If the surrounding workflow is a reusable workflow itself, append ', ${{ inputs.workflow-context }}'
      workflow-context: '"build-with-reusable-workflow", ${{ toJSON(matrix) }}, ${{ inputs.workflow-context }}'
