name: ~ Example Reusable
on:
  workflow_call:
    inputs:
      workflow-context:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env | grep GITHUB_

      - uses: actions/checkout@v4

      - uses: ./
        with:
          workflow-context: ${{ inputs.workflow-context }}
